sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t wokeorange/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wokeorange/docker-react npm run test
