sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t wokeorange/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wokeorange/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-146627625225"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
